// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBdXyP0RxNNtCZBuBhrR_grTOSFKVKsjc',
    appId: '1:1028633904384:web:07b19c58cdd7d171d41fe5',
    messagingSenderId: '1028633904384',
    projectId: 'shopping-7021b',
    authDomain: 'shopping-7021b.firebaseapp.com',
    storageBucket: 'shopping-7021b.firebasestorage.app',
    measurementId: 'G-7NFZBPYPS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFmelTtmc78YZJm8V5jtDCQy86T90j9s',
    appId: '1:1028633904384:android:94943dc82711ddfbd41fe5',
    messagingSenderId: '1028633904384',
    projectId: 'shopping-7021b',
    storageBucket: 'shopping-7021b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOxmyr9yPooZgctPDnQTq0ZDcFGmvuu-c',
    appId: '1:1028633904384:ios:aaa785a7dad72a4ed41fe5',
    messagingSenderId: '1028633904384',
    projectId: 'shopping-7021b',
    storageBucket: 'shopping-7021b.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOxmyr9yPooZgctPDnQTq0ZDcFGmvuu-c',
    appId: '1:1028633904384:ios:aaa785a7dad72a4ed41fe5',
    messagingSenderId: '1028633904384',
    projectId: 'shopping-7021b',
    storageBucket: 'shopping-7021b.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBdXyP0RxNNtCZBuBhrR_grTOSFKVKsjc',
    appId: '1:1028633904384:web:4d444b09855758b3d41fe5',
    messagingSenderId: '1028633904384',
    projectId: 'shopping-7021b',
    authDomain: 'shopping-7021b.firebaseapp.com',
    storageBucket: 'shopping-7021b.firebasestorage.app',
    measurementId: 'G-X4HGDZ84PC',
  );
}
